# Generated by Django 4.2.13 on 2024-05-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Student',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Person',
        ),
    ]
