# Generated by Django 4.2.13 on 2024-05-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='base.student'),
        ),
    ]
