# Generated by Django 4.2.13 on 2024-05-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
    ]
